# $FreeBSD$

PORTNAME=       jrds
PORTVERSION=    20150406
PORTREVISION=   1
CATEGORIES=     net-mgmt java
MASTER_SITES=   GH

MAINTAINER=     bougie@appartland.eu
COMMENT=        Another monitoring application, intentend to be simple to use

DISTFILES+=     ${GH_ACCOUNT}-${PORTNAME}-${PORTVERSION}-${GH_TAGNAME}_GH0.tar.gz

EXTRA_DIST= base64 commonscodec commonsfileupload commonsio commonslogging commonsnet dojo hamcrestcore httpclient httpcore javaxservletapi jettyhttp jettyio jettyjmx jettysecurity jettyserver jettyservlet jettyutil jettywebapp jettyxml jodatime json junit log4j mysqlconnectorjava opendmk_jmxremote_optional_jar postgresql rrd4j slf4japi slf4jlog4j12 snmp4j snmp4jagent wscommonsutil xmlapis xmlrpccommon xmlrpcserver

base64_SUFFIX=                  -2.3.8.jar
base64_SUBDIR=                  net/iharder/base64/jars

commonscodec_REALNAME=          commons-codec
commonscodec_SUFFIX=            -1.9.jar
commonscodec_SUBDIR=            commons-codec/commons-codec/jars

commonsfileupload_REALNAME=     commons-fileupload
commonsfileupload_SUFFIX=       -1.3.1.jar
commonsfileupload_SUBDIR=       commons-fileupload/commons-fileupload/jars

commonsio_REALNAME=             commons-io
commonsio_SUFFIX=               -2.2.jar
commonsio_SUBDIR=               commons-io/commons-io/jars

commonslogging_REALNAME=        commons-logging
commonslogging_SUFFIX=          -1.2.jar
commonslogging_SUBDIR=          commons-logging/commons-logging/jars

commonsnet_REALNAME=            commons-net
commonsnet_SUFFIX=              -3.3.jar
commonsnet_SUBDIR=              commons-net/commons-net/jars

dojo_SUFFIX=                    -1.10.4.zip
dojo_SUBDIR=                    org/dojotoolkit/dojo/zips

hamcrestcore_REALNAME=          hamcrest-core
hamcrestcore_SUFFIX=            -1.3.jar
hamcrestcore_SUBDIR=            org/hamcrest/hamcrest-core/jars

httpclient_SUFFIX=              -4.4.jar
httpclient_SUBDIR=              org/apache/httpcomponents/httpclient/jars

httpcore_SUFFIX=                -4.4.jar
httpcore_SUBDIR=                org/apache/httpcomponents/httpcore/jars

javaxservletapi_REALNAME=       javax.servlet-api
javaxservletapi_SUFFIX=         -3.1.0.jar
javaxservletapi_SUBDIR=         javax/servlet/javax.servlet-api/jars

jettyhttp_REALNAME=             jetty-http
jettyhttp_SUFFIX=               -9.2.0.v20140526.jar
jettyhttp_SUBDIR=               org/eclipse/jetty/jetty-http/jars

jettyio_REALNAME=               jetty-io
jettyio_SUFFIX=                 -9.2.0.v20140526.jar
jettyio_SUBDIR=                 org/eclipse/jetty/jetty-io/jars

jettyjmx_REALNAME=              jetty-jmx
jettyjmx_SUFFIX=                -9.2.0.v20140526.jar
jettyjmx_SUBDIR=                org/eclipse/jetty/jetty-jmx/jars

jettysecurity_REALNAME=         jetty-security
jettysecurity_SUFFIX=           -9.2.0.v20140526.jar
jettysecurity_SUBDIR=           org/eclipse/jetty/jetty-security/jars

jettyserver_REALNAME=           jetty-server
jettyserver_SUFFIX=             -9.2.0.v20140526.jar
jettyserver_SUBDIR=             org/eclipse/jetty/jetty-server/jars

jettyservlet_REALNAME=          jetty-servlet
jettyservlet_SUFFIX=            -9.2.0.v20140526.jar
jettyservlet_SUBDIR=            org/eclipse/jetty/jetty-servlet/jars

jettyutil_REALNAME=             jetty-util
jettyutil_SUFFIX=               -9.2.0.v20140526.jar
jettyutil_SUBDIR=               org/eclipse/jetty/jetty-util/jars

jettywebapp_REALNAME=           jetty-webapp
jettywebapp_SUFFIX=             -9.2.0.v20140526.jar
jettywebapp_SUBDIR=             org/eclipse/jetty/jetty-webapp/jars

jettyxml_REALNAME=              jetty-xml
jettyxml_SUFFIX=                -9.2.0.v20140526.jar
jettyxml_SUBDIR=                org/eclipse/jetty/jetty-xml/jars

jodatime_REALNAME=              joda-time
jodatime_SUFFIX=                -2.3.jar
jodatime_SUBDIR=                joda-time/joda-time/jars

json_SUFFIX=                    -20140107.jar
json_SUBDIR=                    org/json/json/jars

junit_SUFFIX=                   -4.11.jar
junit_SUBDIR=                   junit/junit/jars

log4j_SUFFIX=                   -1.2.17.jar
log4j_SUBDIR=                   log4j/log4j/bundles

mysqlconnectorjava_REALNAME=    mysql-connector-java
mysqlconnectorjava_SUFFIX=      -5.1.30.jar
mysqlconnectorjava_SUBDIR=      mysql/mysql-connector-java/jars

opendmk_jmxremote_optional_jar_SUFFIX= -1.0-b01-ea.jar
opendmk_jmxremote_optional_jar_SUBDIR= org/glassfish/external/opendmk_jmxremote_optional_jar/jars

postgresql_SUFFIX=              -8.4-702.jdbc4.jar
postgresql_SUBDIR=              postgresql/postgresql/jars

rrd4j_SUFFIX=                   -2.3-SNAPSHOT.jar
rrd4j_SUBDIR=                   org/rrd4j/rrd4j/jars

slf4japi_REALNAME=              slf4j-api
slf4japi_SUFFIX=                -1.7.7.jar
slf4japi_SUBDIR=                org/slf4j/slf4j-api/jars

slf4jlog4j12_REALNAME=          slf4j-log4j12
slf4jlog4j12_SUFFIX=            -1.7.7.jar
slf4jlog4j12_SUBDIR=            org/slf4j/slf4j-log4j12/jars

snmp4j_SUFFIX=                  -2.2.5.jar
snmp4j_SUBDIR=                  org/snmp4j/snmp4j/jars

snmp4jagent_REALNAME=           snmp4j-agent
snmp4jagent_SUFFIX=             -2.1.1.jar
snmp4jagent_SUBDIR=             org/snmp4j/snmp4j-agent/jars

wscommonsutil_REALNAME=         ws-commons-util
wscommonsutil_SUFFIX=           -1.0.2.jar
wscommonsutil_SUBDIR=           org/apache/ws/commons/util/ws-commons-util/jars

xmlapis_REALNAME=               xml-apis
xmlapis_SUFFIX=                 -1.0.b2.jar
xmlapis_SUBDIR=                 xml-apis/xml-apis/jars

xmlrpccommon_REALNAME=          xmlrpc-common
xmlrpccommon_SUFFIX=            -3.1.3.jar
xmlrpccommon_SUBDIR=            org/apache/xmlrpc/xmlrpc-common/jars

xmlrpcserver_REALNAME=          xmlrpc-server
xmlrpcserver_SUFFIX=            -3.1.3.jar
xmlrpcserver_SUBDIR=            org/apache/xmlrpc/xmlrpc-server/jars

MASTER_IVY=     http://jrds.fr/maven2/
.for dist in ${EXTRA_DIST}
.ifdef ${dist}_REALNAME
DISTFILES+=     ${${dist}_REALNAME}${${dist}_SUFFIX}:${dist}
MASTER_SITES+=  ${MASTER_IVY}/${${dist}_SUBDIR}/:${dist}
.else
DISTFILES+=     ${dist}${${dist}_SUFFIX}:${dist}
MASTER_SITES+=  ${MASTER_IVY}/${${dist}_SUBDIR}/:${dist}
.endif
.endfor

EXTRACT_ONLY=   ${GH_ACCOUNT}-${PORTNAME}-${PORTVERSION}-${GH_TAGNAME}_GH0.tar.gz

LICENSE=        GPLv3

USE_GITHUB=     yes
GH_ACCOUNT=     fbacchella
GH_PROJECT=     jrds
GH_TAGNAME=     febd4fd4c7986eba7e510c69fc622fde5d855fc1

DIST_SUBDIR=    ${PORTNAME}

USE_JAVA=       yes
JAVA_VERSION=   1.7+
JAVA_BUILD=     yes
JAVA_RUN=       yes
USE_ANT=        yes
EXTRACT_DEPENDS= unzip:${PORTSDIR}/archivers/unzip
BUILD_DEPENDS=  ant:${PORTSDIR}/devel/apache-ant

USE_RC_SUBR=    ${PORTNAME}
SUB_LIST=       JAVA_HOME=${JAVA_HOME}

post-extract:
	${MKDIR} ${WRKSRC}/lib ${WRKSRC}/libtest ${WRKSRC}/libjetty ${WRKSRC}/build ${WRKSRC}/libprobes
	# Copy all library in lib dir
.for dist in ${DISTFILES}
	${CP} ${DISTDIR}/${DIST_SUBDIR}/`echo ${dist} | cut -d: -f1` ${WRKSRC}/lib
.endfor
	# copy a peace of lib in libjetty directory
	${CP} ${WRKSRC}/lib/log4j* ${WRKSRC}/lib/slf4j-* ${WRKSRC}/lib/javax.servlet* ${WRKSRC}/lib/jetty-* ${WRKSRC}/libjetty
	# unzip dojo*.zip
	unzip -d ${WRKSRC}/lib ${DISTDIR}/${DIST_SUBDIR}/dojo${dojo_SUFFIX} "dojo-release-*/*"
	${MV} ${WRKSRC}/lib/dojo-release-* ${WRKSRC}/lib/dojo

do-build:
	cd ${WRKSRC} && ant && ant jetty

do-install:
	${MKDIR} ${STAGEDIR}${DATADIR}/webapp
	${TAR} -xpf ${WRKSRC}/build/jrds.tar -C ${STAGEDIR}${DATADIR}/webapp
	# Copy config files
	${MKDIR} ${STAGEDIR}${ETCDIR}
	${INSTALL_DATA} ${PATCHDIR}/jrds.properties.sample ${STAGEDIR}${ETCDIR} && \
		${REINPLACE_CMD} -e 's#%%ETCDIR%%#${ETCDIR}#g' ${STAGEDIR}${ETCDIR}/jrds.properties.sample && \
		${REINPLACE_CMD} -e 's#%%PREFIX%%#${PREFIX}#g' ${STAGEDIR}${ETCDIR}/jrds.properties.sample && \
		${REINPLACE_CMD} -e 's#%%PORTNAME%%#${PORTNAME}#g' ${STAGEDIR}${ETCDIR}/jrds.properties.sample
	${MKDIR} -p ${STAGEDIR}${PREFIX}/var/lib/${PORTNAME} ${STAGEDIR}${PREFIX}/var/log/${PORTNAME} ${STAGEDIR}${PREFIX}/var/run/${PORTNAME}

.include <bsd.port.mk>
